### ISSUE TITLE
Why metrics['slaviolations'] can only be 1?

### ISSUE THREAD

**Issue by Jingbo-leo** [imperial-qore/COSCO#10]
Thanks a lot for your open source code. I have some doubts. I found that `metrics['slaviolations'] = len(np.where([c.destroyAt > c.sla for c in destroyed]))` in the stats.py file. No matter how many `c.destroyAt > c.sla`, this `metrics['slaviolations']` can only be 1 each time.  Is this correct?Hope to hear from you, thank you very much.

**Comment by shreshthtuli** [comment]
Thanks for your interest in our project. `np.where` gives a list of indices where the input condition is true. Thus, `len(np.where([...])` would give us the number of completed tasks in that interval for which the destroy time is higher than the service level agreement.

**Comment by Jingbo-leo** [comment]
Thank you very much for your reply. I understand what it means. But writing like this will result in `len(np.where([...])` can only be 1 each time, no matter how many `c.destroyAt > c.sla`.  The output of an example is as follows.
`destroyed = [] `
`[c.destroyAt > c.sla for c in destroyed] output is:  []`
`np.where([c.destroyAt > c.sla for c in destroyed]) output is:  (array([], dtype=int64),)`
`len(np.where([c.destroyAt > c.sla for c in destroyed])) output is :  1`

**Comment by shreshthtuli** [comment]
Thanks for raising this. It has been fixed.
