### ISSUE TITLE
How to set VMs in Vagrant

### ISSUE THREAD

**Issue by Chenhait** [imperial-qore/COSCO#13]
Hi, Tuli.
Thank you so much for this wonderful code!
I read the wiki, for the Vagrant, however, I did not find the method of setting VMs in Vagrant.
when i run 
python main.py -e Vagrant -m 0
it seems stopped here
resp = requests.get("http://"+IP+":8081/request", data=json.dumps(payload))
i have no idea about 8081.
I wonder if I miss some tutoril about how to set VMs in vagrant
thank you very much if any advance!!!

**Comment by shivupoojar** [comment]
Hi Chenhat,

Thanks for your interest in COSCO.
Can you check with this setting:
https://github.com/imperial-qore/COSCO/wiki/Running-Experiments:-Vagrant-Environment#known-errors
Thanks
Shiva

**Comment by Chenhait** [comment]
Hi, Tuli.
Thank you so much for your quickly apply!!! It is so nice of you!!!
So, your mean is that I do not need install the virtual machines by myself,
instead, this code will config automaticly.
However,

if I do nothing and run 
python main.py -e Vagrant -m 0
the error is 
requests.exceptions.ConnectionError: HTTPConnectionPool(host='192.168.122.2', port=8081): Max retries exceeded with url: /request (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f03b740d250>: Failed to establish a new connection: [Errno 110] Connection timed out'))

if I change the BASE_IPS in framework/agent/codes.py to host IP address
the error is
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='172.31.162.2', port=8081): Max retries exceeded with url: /request (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f51186e6890>: Failed to establish a new connection: [Errno 111] Connection refused'))

I wonder where the port 8081 is exposed in this code?
Thank you very much if any advance!!!

hope you good everyday!
