### ISSUE TITLE
Workload description 

### ISSUE THREAD

**Issue by ndganesan** [imperial-qore/COSCO#7]
Could you please help me to know how the scheduling time for each application is defined in the COSCO simulator. I checked the Bitbrains and Azur workload datasets as well where the scheduling time and end time are not defined. Also, could you please explain to me how the container is allocated in the COSCO simulator?

**Comment by shreshthtuli** [comment]
Scheduling time is calculated initially 120 of main.py. Container images are present in all worker nodes at the time of installation. For allocation, the corresponding container is initialized at the target worker node.
